### ISSUE TITLE
win8执行react-web init <projectName>失败是什么原因呢?

### ISSUE THREAD

**Issue by zhuxindaba** [taobaofed/react-web#105]
node版本是5.7.0
```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)
```

**Comment by yuanyan** [comment]
可能是win8下没有找到npm可执行文件
