### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by zaynyatyi** [taobaofed/react-web#125]
I'm getting unexpected token error in rn-router module when trying to bundle my app

`ERROR in ./~/rn-router/src/Router.js
Module parse failed: /Users/pro13/dev/dubit_dev/ks/kingdomscenereact/node_modules/rn-router/src/Router.js Unexpected token (335:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (335:6)
    at Parser.pp.raise (/Users/pro13/dev/dubit_dev/ks/kingdomscenereact/node_modules/webpack/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.unexpected (/Users/pro13/dev/dubit_dev/ks/kingdomscenereact/node_modules/webpack/node_modules/acorn/dist/acorn.js:1490:8)
    at Parser.pp.parseExprAtom (/Users/pro13/dev/dubit_dev/ks/kingdomscenereact/node_modules/webpack/node_modules/acorn/dist/acorn.js:333:12)
    at Parser.pp.parseExprSubscripts (/Users/pro13/dev/dubit_dev/ks/kingdomscenereact/node_modules/webpack/node_modules/acorn/dist/acorn.js:228:19)
    at Parser.pp.parseMaybeUnary (/Users/pro13/dev/dubit_dev/ks/kingdomscenereact/node_modules/webpack/node_modules/acorn/dist/acorn.js:207:17)
    at Parser.pp.parseExprOps (/Users/pro13/dev/dubit_dev/ks/kingdomscenereact/node_modules/webpack/node_modules/acorn/dist/acorn.js:154:19)
    at Parser.pp.parseMaybeConditional (/Users/pro13/dev/dubit_dev/ks/kingdomscenereact/node_modules/webpack/node_modules/acorn/dist/acorn.js:136:19)
    at Parser.pp.parseMaybeAssign (/Users/pro13/dev/dubit_dev/ks/kingdomscenereact/node_modules/webpack/node_modules/acorn/dist/acorn.js:112:19)
    at Parser.pp.parseParenAndDistinguishExpression (/Users/pro13/dev/dubit_dev/ks/kingdomscenereact/node_modules/webpack/node_modules/acorn/dist/acorn.js:376:28)
    at Parser.pp.parseExprAtom (/Users/pro13/dev/dubit_dev/ks/kingdomscenereact/node_modules/webpack/node_modules/acorn/dist/acorn.js:307:19)
    at Parser.pp.parseExprSubscripts (/Users/pro13/dev/dubit_dev/ks/kingdomscenereact/node_modules/webpack/node_modules/acorn/dist/acorn.js:228:19)
    at Parser.pp.parseMaybeUnary (/Users/pro13/dev/dubit_dev/ks/kingdomscenereact/node_modules/webpack/node_modules/acorn/dist/acorn.js:207:17)
    at Parser.pp.parseExprOps (/Users/pro13/dev/dubit_dev/ks/kingdomscenereact/node_modules/webpack/node_modules/acorn/dist/acorn.js:154:19)
    at Parser.pp.parseMaybeConditional (/Users/pro13/dev/dubit_dev/ks/kingdomscenereact/node_modules/webpack/node_modules/acorn/dist/acorn.js:136:19)
    at Parser.pp.parseMaybeAssign (/Users/pro13/dev/dubit_dev/ks/kingdomscenereact/node_modules/webpack/node_modules/acorn/dist/acorn.js:112:19)
    at Parser.pp.parseExpression (/Users/pro13/dev/dubit_dev/ks/kingdomscenereact/node_modules/webpack/node_modules/acorn/dist/acorn.js:88:19)
 @ ./~/rn-router/index.js 4:10-33`

Here is the part of code with error, it's just JSX

`    return (
      <Navigator
        ref="navigator"
        {...navProps}
      />
    );`

Line with <Navigator is 335 one, with error. What could be wrong here? Other modules are fine.

Thanks

**Comment by flyskywhy** [comment]
@zaynyatyi , it's solved in issue #138 , and in your case, base on #138 , you should change webpack.config.js from

    exclude: [/node_modules/]

to 

    exclude: [/(node_modules\/(?!rn-router))/]
