### ISSUE TITLE
react-web init   project error

### ISSUE THREAD

**Issue by aopui** [taobaofed/react-web#131]
$ react-web init test3
prompt: Directory test3 already exists. Continue?:  (no) y
This will walk you through creating a new React Web project in D:\reactWebTest\test3
Installing react-web package from npm...
Setting up new React Web app in D:\reactWebTest\test3
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by aopui** [comment]
with node 4.4.0 or 4.4.6 or 4.4.7

**Comment by aopui** [comment]
有没有 官方QQ群呢

**Comment by aopui** [comment]
没人管哎

**Comment by yawetse** [comment]
I recommend using NVM and then using node 5.x

**Comment by flyskywhy** [comment]
@aopui @yawetse , this issue was fixed by #174
