### ISSUE TITLE
在react native项目中升级为web版本的时候报错

### ISSUE THREAD

**Issue by 791060555** [taobaofed/react-web#132]
D:>react-web init mobile_new
prompt: Directory mobile_new already exists. Continue?:  (no) y
This will walk you through creating a new React Web project in D:\mobile_new
Installing react-web package from npm...
Setting up new React Web app in D:\mobile_new
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by flyskywhy** [comment]
@791060555 , this issue was fixed in #174
