### ISSUE TITLE
windows环境 react-web init a 报错

### ISSUE THREAD

**Issue by bamboox** [taobaofed/react-web#147]
$ react-web init a
This will walk you through creating a new React Web project in G:\rnpro\a
Installing react-web package from npm...
Setting up new React Web app in G:\rnpro\a
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:873:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by yuanyan** [comment]
Could get help with http://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js .

**Comment by flyskywhy** [comment]
@bamboox @yuanyan , this issue was fixed in #174
