### ISSUE TITLE
Cannot resolve module 'ReactJsonp'

### ISSUE THREAD

**Issue by sduqlsc** [taobaofed/react-web#173]
any idea about this?

```
var React = require('react-native');
var {
    Platform,
    Component,
} = React;
var fetch = Platform.OS === 'web'? require('ReactJsonp'): require('ReactFetch');
```

**Comment by yuanyan** [comment]
Is HasteResolverPlugin not install right?

**Comment by sduqlsc** [comment]
@yuanyan here is the js file:
[webpack.config.txt](https://github.com/taobaofed/react-web/files/518655/webpack.config.txt)


i believe there is no wrong config.

**Comment by flyskywhy** [comment]
@sduqlsc @yuanyan , this issue was fixed in PR https://github.com/yuanyan/haste-resolver/pull/2 which is described as "the remaining react-web start error on Windows" in PR #174 when `react-web start`, and with #174 , `react-web init` also worked well on Windows.

**Comment by sduqlsc** [comment]
@flyskywhy thanks for the reply. so exactly what should i do next?

**Comment by flyskywhy** [comment]
for right now, because PR https://github.com/yuanyan/haste-resolver/pull/2 has not been merged, you need replace haste-resolver npm version by my git version:

    npm install git+https://github.com/flyskywhy/haste-resolver

and replace

    exclude: /(node_modules\/(?!react))/

to

    exclude: [path.sep === '/' ? /(node_modules\/(?!react))/ : /(node_modules\\(?!react))/]

in `react-web/local-cli/generator-web/templates/webpack.config.js` ref to PR #174

**Comment by sduqlsc** [comment]
@flyskywhy has done as above and update to react-web v0.4.1, but got following error:
E:\Project\Node\RN\node_modules\react-web\node_modules\promise\lib\done.js:10
      throw err;
      ^

Error: Cannot find module './lib/'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\Project\Node\RN\node_modules\haste-resolver\index.js:1:18)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\Project\Node\RN\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (E:\Project\Node\RN\node_modules\haste-resolver-webpack-plugin\HasteResolverPlugin.js:9:16)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\Project\Node\RN\node_modules\babel-register\lib\node.js:152:7)

**Comment by flyskywhy** [comment]
@sduqlsc , yes, I also met this `Error: Cannot find module './lib/'` on my Win7, and then I found it is also because @yuanyan has not merge PR https://github.com/yuanyan/haste-resolver/pull/2 and publish to npmjs.com a new haste-resolver version, so instead of the useless `npm install git+https://github.com/flyskywhy/haste-resolver` I guessed before, please:

    cd \Project\Node\
    git clone https://github.com/flyskywhy/haste-resolver
    cd haste-resolver
    npm install
    cd ..\RN\
    npm install denodeify throat

then copy `\Project\Node\haste-resolver\lib\` to `\Project\Node\RN\node_modules\haste-resolver\lib\`

**Comment by sduqlsc** [comment]
@flyskywhy thanks for the reply with the details. Will report later.

**Comment by sduqlsc** [comment]
@flyskywhy succeed, you saved my time buddy, great job!
