### ISSUE TITLE
运行react-web start，所有图片都报错

### ISSUE THREAD

**Issue by EleTeam** [taobaofed/react-web#181]
图片在ios和android下是可以显示的，代码如下
               <Image
                    style={{flex: 1, width: width, height: height}}
                    source={require('../images/ic_welcome.jpg')}
                />

报错如下：
ERROR in ./app/images/ic_welcome.jpg
Module parse failed: /Users/tony/Desktop/Develop/WebStormProjects/ShopReactNative/app/images/ic_welcome.jpg Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '�' (1:0)
    at Parser.pp$4.raise (/Users/tony/Desktop/Develop/WebStormProjects/ShopReactNative/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (/Users/tony/Desktop/Develop/WebStormProjects/ShopReactNative/node_modules/webpack/node_modules/acorn/dist/acorn.js:2756:10)
    at Parser.pp$7.readToken (/Users/tony/Desktop/Develop/WebStormProjects/ShopReactNative/node_modules/webpack/node_modules/acorn/dist/acorn.js:2477:17)
    at Parser.pp$7.nextToken (/Users/tony/Desktop/Develop/WebStormProjects/ShopReactNative/node_modules/webpack/node_modules/acorn/dist/acorn.js:2468:15)
    at Parser.parse (/Users/tony/Desktop/Develop/WebStormProjects/ShopReactNative/node_modules/webpack/node_modules/acorn/dist/acorn.js:515:10)
    at Object.parse (/Users/tony/Desktop/Develop/WebStormProjects/ShopReactNative/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/tony/Desktop/Develop/WebStormProjects/ShopReactNative/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/tony/Desktop/Develop/WebStormProjects/ShopReactNative/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/tony/Desktop/Develop/WebStormProjects/ShopReactNative/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/tony/Desktop/Develop/WebStormProjects/ShopReactNative/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/tony/Desktop/Develop/WebStormProjects/ShopReactNative/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/tony/Desktop/Develop/WebStormProjects/ShopReactNative/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/tony/Desktop/Develop/WebStormProjects/ShopReactNative/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:404:3)
 @ ./app/pages/Splash.js 53:7-42

**Comment by yuanyan** [comment]
Webpack loader配置默认没有加上图片
