### ISSUE TITLE
Can you support the dimensions components in react-native

### ISSUE THREAD

**Issue by txs** [taobaofed/react-web#210]
the current version doesn't support it! Please help!

**Comment by txs** [comment]
and here's the error code I got

`ERROR in ./app/components/tinder/Matches.js
Module not found: Error: Cannot resolve module 'Dimensions' in C:\Users\txshon\Documents\wecareStart\Starter\app\components\tinder
 @ ./app/components/tinder/Matches.js 8:11-32

ERROR in ./app/components/accounts/_accountsStyles.js
Module not found: Error: Cannot resolve module 'Dimensions' in C:\Users\txshon\Documents\wecareStart\Starter\app\components\accounts
 @ ./app/components/accounts/_accountsStyles.js 9:11-32

ERROR in ./~/@exponent/react-native-navigator/ExNavigator.js
Module parse failed: C:\Users\txshon\Documents\wecareStart\Starter\node_modules\@exponent\react-native-navigator\ExNavigator.js Unexpected token (23:12)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (23:12)
    at Parser.pp$4.raise (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.expectContextual (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:558:41)
    at Parser.pp$1.parseImport (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:1240:12)
    at Parser.pp$1.parseStatement (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:719:46)
    at Parser.pp$1.parseTopLevel (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\webpack\lib\Parser.js:902:15)
    at NormalModule.<anonymous> (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\webpack\lib\NormalModule.js:104:16)
    at NormalModule.onModuleBuild (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at C:\Users\txshon\Documents\wecareStart\Starter\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at C:\Users\txshon\Documents\wecareStart\Starter\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:415:3)
 @ ./app/components/Main.js 18:26-69

ERROR in ./~/apsl-react-native-button/Button.js
Module parse failed: C:\Users\txshon\Documents\wecareStart\Starter\node_modules\apsl-react-native-button\Button.js Unexpected token (36:2)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (36:2)
    at Parser.pp$4.raise (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseExprList (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:2165:22)
    at Parser.pp$3.parseSubscripts (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:1741:35)
    at Parser.pp$3.parseExprSubscripts (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:1718:17)
    at Parser.pp$3.parseMaybeUnary (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parsePropertyValue (C:\Users\txshon\Documents\wecareStart\Starter\node_modules\acorn\dist\acorn.js:1998:89)
 @ ./app/components/NoConnection.js 11:27-62

ERROR in ./~/react-web/Libraries/DrawerLayout/DrawerLayout.web.js
Module build failed: SyntaxError: C:/Users/txshon/Documents/wecareStart/Starter/node_modules/react-web/Libraries/DrawerLayout/DrawerLayout.web.js: A semicolon is required after a class property (32:3)

  30 |     Left: 'left',
  31 |     Right: 'right'
> 32 |   }
     |    ^
  33 |
  34 |   static defaultProps = {
  35 |     drawerWidth: 0,

 @ ./~/react-web/Libraries/index.js 16:500-528

ERROR in ./~/react-web/Libraries/ActivityIndicator/ActivityIndicator.web.js
Module build failed: SyntaxError: C:/Users/txshon/Documents/wecareStart/Starter/node_modules/react-web/Libraries/ActivityIndicator/ActivityIndicator.web.js: A semicolon is required after a class property (52:3)

  50 |       'large',
  51 |     ]),
> 52 |   }
     |    ^
  53 |
  54 |   static defaultProps = {
  55 |     animating: true,

 @ ./~/react-web/Libraries/index.js 16:366-399

ERROR in ./~/react-web/Libraries/Image/Image.web.js
Module build failed: SyntaxError: C:/Users/txshon/Documents/wecareStart/Starter/node_modules/react-web/Libraries/Image/Image.web.js: A semicolon is required after a class property (17:37)

  15 |
  16 | class Image extends Component {
> 17 |   static resizeMode = ImageResizeMode
     |                                      ^
  18 |
  19 |   static contextTypes = {
  20 |     isInAParentText: React.PropTypes.bool

 @ ./~/react-web/Libraries/index.js 16:612-633

ERROR in ./~/react-web/Libraries/ListView/ListView.web.js
Module build failed: SyntaxError: C:/Users/txshon/Documents/wecareStart/Starter/node_modules/react-web/Libraries/ListView/ListView.web.js: A semicolon is required after a class property (78:40)

  76 | class ListView extends Component {
  77 |
> 78 |   static DataSource = ListViewDataSource
     |                                         ^
  79 |
  80 |   /**
  81 |    * You must provide a renderRow function. If you omit any of the other render

 @ ./~/react-web/Libraries/index.js 16:706-730

ERROR in ./~/react-web/Libraries/Picker/Picker.web.js
Module build failed: SyntaxError: C:/Users/txshon/Documents/wecareStart/Starter/node_modules/react-web/Libraries/Picker/Picker.web.js: A semicolon is required after a class property (18:3)

  16 |     onValueChange: PropTypes.func,
  17 |     selectedValue: PropTypes.any, // string or integer basically
> 18 |   }
     |    ^
  19 |
  20 |   _onChange(event) {
  21 |     // shim the native event

 @ ./~/react-web/Libraries/index.js 16:1104-1126

ERROR in ./~/react-web/Libraries/SegmentedControl/SegmentedControl.web.js
Module build failed: SyntaxError: C:/Users/txshon/Documents/wecareStart/Starter/node_modules/react-web/Libraries/SegmentedControl/SegmentedControl.web.js: A semicolon is required after a class property (60:3)

  58 |      */
  59 |     momentary: PropTypes.bool
> 60 |   }
     |    ^
  61 |
  62 |   static defaultProps = {
  63 |     values: [],

 @ ./~/react-web/Libraries/index.js 16:1439-1471

ERROR in ./~/react-web/Libraries/Switch/Switch.web.js
Module build failed: SyntaxError: C:/Users/txshon/Documents/wecareStart/Starter/node_modules/react-web/Libraries/Switch/Switch.web.js: A semicolon is required after a class property (24:3)

  22 |     thumbTintColor: PropTypes.string,
  23 |     tintColor: PropTypes.string
> 24 |   }
     |    ^
  25 |
  26 |   static defaultProps = {
  27 |     onTintColor: '#00e158',

 @ ./~/react-web/Libraries/index.js 16:1659-1681

ERROR in ./~/react-web/Libraries/TextInput/TextInput.web.js
Module build failed: SyntaxError: C:/Users/txshon/Documents/wecareStart/Starter/node_modules/react-web/Libraries/TextInput/TextInput.web.js: A semicolon is required after a class property (39:3)

  37 |     keyboardType: 'default',
  38 |     autoFocus: false
> 39 |   }
     |    ^
  40 |
  41 |   _onBlur(e) {
  42 |     const { onBlur } = this.props;

 @ ./~/react-web/Libraries/index.js 16:2046-2071

ERROR in ./~/react-web/Libraries/Touchable/TouchableHighlight.web.js
Module build failed: SyntaxError: C:/Users/txshon/Documents/wecareStart/Starter/node_modules/react-web/Libraries/Touchable/TouchableHighlight.web.js: A semicolon is required after a class property (62:3)

  60 |      */
  61 |     onHideUnderlay: React.PropTypes.func,
> 62 |   }
     |    ^
  63 |
  64 |   static defaultProps = DEFAULT_PROPS
  65 |

 @ ./~/react-web/Libraries/index.js 16:2360-2394

ERROR in ./~/react-web/Libraries/Touchable/TouchableOpacity.web.js
Module build failed: SyntaxError: C:/Users/txshon/Documents/wecareStart/Starter/node_modules/react-web/Libraries/Touchable/TouchableOpacity.web.js: A semicolon is required after a class property (71:3)

  69 |     ...this.touchableGetInitialState(),
  70 |     anim: new Animated.Value(1),
> 71 |   }
     |    ^
  72 |
  73 |   // componentDidMount: function() {
  74 |   //   // ensurePositiveDelayProps(this.props);

 @ ./~/react-web/Libraries/index.js 16:2501-2533

ERROR in ./~/react-web/Libraries/Touchable/TouchableWithoutFeedback.web.js
Module build failed: SyntaxError: C:/Users/txshon/Documents/wecareStart/Starter/node_modules/react-web/Libraries/Touchable/TouchableWithoutFeedback.web.js: A semicolon is required after a class property (61:3)

  59 |      */
  60 |     delayLongPress: React.PropTypes.number,
> 61 |   }
     |    ^
  62 |
  63 |   state = this.touchableGetInitialState()
  64 |

 @ ./~/react-web/Libraries/index.js 16:2644-2684

ERROR in ./~/react-web/Libraries/Touchable/TouchableBounce.web.js
Module build failed: SyntaxError: C:/Users/txshon/Documents/wecareStart/Starter/node_modules/react-web/Libraries/Touchable/TouchableBounce.web.js: A semicolon is required after a class property (48:3)

  46 |     // the function passed is called after the animation is complete
  47 |     onPressAnimationComplete: React.PropTypes.func,
> 48 |   }
     |    ^
  49 |
  50 |   state = {
  51 |     ...this.touchableGetInitialState(),

 @ ./~/react-web/Libraries/index.js 16:2802-2833

ERROR in ./~/react-web/Libraries/RefreshControl/RefreshControl.web.js
Module build failed: SyntaxError: C:/Users/txshon/Documents/wecareStart/Starter/node_modules/react-web/Libraries/RefreshControl/RefreshControl.web.js: A semicolon is required after a class property (21:40)

  19 | class RefreshControl extends Component {
  20 |
> 21 |   static SIZE = RefreshLayoutConsts.SIZE
     |                                         ^
  22 |
  23 |   componentDidMount() {
  24 |     this._lastNativeRefreshing = this.props.refreshing;

 @ ./~/react-web/Libraries/index.js 16:2932-2962

ERROR in ./~/react-web/Libraries/ViewPager/ViewPager.web.js
Module build failed: SyntaxError: C:/Users/txshon/Documents/wecareStart/Starter/node_modules/react-web/Libraries/ViewPager/ViewPager.web.js: A semicolon is required after a class property (61:3)

  59 |       'on-drag'
  60 |     ])
> 61 |   }
     |    ^
  62 |
  63 |   static defaultProps = {
  64 |     initialPage: 0

 @ ./~/react-web/Libraries/index.js 16:3141-3166

ERROR in ./~/react-web/Libraries/Navigator/NavigatorBreadcrumbNavigationBar.js
Module build failed: SyntaxError: C:/Users/txshon/Documents/wecareStart/Starter/node_modules/react-web/Libraries/Navigator/NavigatorBreadcrumbNavigationBar.js: A semicolon is required after a class property (78:3)

  76 |     }),
  77 |     style: View.propTypes.style,
> 78 |   }
     |    ^
  79 |
  80 |   static statics = {
  81 |     Styles: NavigatorBreadcrumbNavigationBarStyles,

 @ ./~/react-web/Libraries/Navigator/Navigator.web.js 17:43-91

ERROR in ./~/react-web/Libraries/Navigator/NavigatorNavigationBar.js
Module build failed: SyntaxError: C:/Users/txshon/Documents/wecareStart/Starter/node_modules/react-web/Libraries/Navigator/NavigatorNavigationBar.js: A semicolon is required after a class property (62:3)

  60 |     navigationStyles: PropTypes.object,
  61 |     style: View.propTypes.style,
> 62 |   }
     |    ^
  63 |
  64 |   static statics = {
  65 |     Styles: NavigatorNavigationBarStyles,

 @ ./~/react-web/Libraries/Navigator/Navigator.web.js 18:33-71

ERROR in ./~/react-web/Libraries/Portal/Portal.web.js
Module build failed: SyntaxError: C:/Users/txshon/Documents/wecareStart/Starter/node_modules/react-web/Libraries/Portal/Portal.web.js: A semicolon is required after a class property (85:22)

  83 |   }
  84 |
> 85 |   state = {modals: {}}
     |                       ^
  86 |
  87 |   _showModal(tag: string, component: any) {
  88 |     // We are about to open first modal, so Portal will appear.
`

**Comment by cssivision** [comment]
will support it soon
