### ISSUE TITLE
When i excute 'react-web start' and show a error `output.path` needs to be an absolute path or `/`.

### ISSUE THREAD

**Issue by yy7054wyq5** [taobaofed/react-web#232]
```
    at Object.setFs (D:\WWW\react-native-web-demo\node_modules\webpack-dev-middleware\lib\Shared.js:88:11)
    at Shared (D:\WWW\react-native-web-demo\node_modules\webpack-dev-middleware\lib\Shared.js:214:8)
    at module.exports (D:\WWW\react-native-web-demo\node_modules\webpack-dev-middleware\middleware.js:22:15)
    at new Server (D:\WWW\react-native-web-demo\node_modules\webpack-dev-server\lib\Server.js:54:20)
    at _server (D:/WWW/react-native-web-demo/node_modules/react-web/local-cli/server.js:54:3)
    at D:/WWW/react-native-web-demo/node_modules/react-web/local-cli/server.js:22:5
    at tryCallTwo (D:\WWW\react-native-web-demo\node_modules\react-web\node_modules\promise\lib\core.js:45:5)
    at doResolve (D:\WWW\react-native-web-demo\node_modules\react-web\node_modules\promise\lib\core.js:171:13)
    at new Promise (D:\WWW\react-native-web-demo\node_modules\react-web\node_modules\promise\lib\core.js:65:3)
    at Array.server (D:/WWW/react-native-web-demo/node_modules/react-web/local-cli/server.js:21:10)
```

**Comment by yy7054wyq5** [comment]
https://github.com/brianneisler/react-web-example
