### ISSUE TITLE
react-web init projectName error

### ISSUE THREAD

**Issue by jlf1103** [taobaofed/react-web#271]
react-native init test 之后
初始化一直提示找不到cli.js
`➜  github react-web init test
prompt: Directory test already exists. Continue?:  (no) yes
This will walk you through creating a new React Web project in /Users/L/Code/github/test
Installing react-web package from npm...
module.js:557
    throw err;
    ^

Error: Cannot find module '/Users/L/Code/github/test/node_modules/react-web/cli.js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at /usr/local/lib/node_modules/react-web-cli/index.js:225:15
    at ChildProcess.exithandler (child_process.js:264:7)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)`

**Comment by yuanyan** [comment]
感谢反馈，已经不推荐使用 react-web init 项目，cli.js 这个文件会发版本来推荐最新的更简单的使用方式
