### ISSUE TITLE
文件冲突

### ISSUE THREAD

**Issue by moyaying** [taobaofed/react-web#47]
Error building DependencyGraph:
 Error: Naming collision detected: /Users/aipai/project/mygithub/demo/AwesomeProject/node_modules/react-web/node_modules/fbjs/flow/include/containsNode.js collides with /Users/aipai/project/mygithub/demo/AwesomeProject/node_modules/react-native/node_modules/fbjs/lib/containsNode.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
    at tryCallOne (/Users/aipai/project/mygithub/demo/AwesomeProject/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/aipai/project/mygithub/demo/AwesomeProject/node_modules/react-native/node_modules/promise/lib/core.js:123:15
    at flush (/Users/aipai/project/mygithub/demo/AwesomeProject/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

**Comment by gre** [comment]
see https://github.com/facebook/react-native/issues/5390#issuecomment-172679236

**Comment by yuanyan** [comment]
@moyaying Fixed?
