### ISSUE TITLE
[Error] run demo error

### ISSUE THREAD

**Issue by Richard-Cao** [taobaofed/react-web#65]
ERROR in ./index.ios.js
Module build failed: ReferenceError: [BABEL] /Users/caolicheng/workspace/react-native-web-example/index.ios.js: Unknown option: base.stage
    at Logger.error (/Users/caolicheng/workspace/react-native-web-example/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/caolicheng/workspace/react-native-web-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:289:18)
    at OptionManager.init (/Users/caolicheng/workspace/react-native-web-example/node_modules/babel-core/lib/transformation/file/options/option-manager.js:481:10)
    at File.initOptions (/Users/caolicheng/workspace/react-native-web-example/node_modules/babel-core/lib/transformation/file/index.js:211:75)
    at new File (/Users/caolicheng/workspace/react-native-web-example/node_modules/babel-core/lib/transformation/file/index.js:129:22)
    at Pipeline.transform (/Users/caolicheng/workspace/react-native-web-example/node_modules/babel-core/lib/transformation/pipeline.js:48:16)
    at transpile (/Users/caolicheng/workspace/react-native-web-example/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/caolicheng/workspace/react-native-web-example/node_modules/babel-loader/index.js:88:12)
 @ multi main
webpack: bundle is now VALID.

**Comment by Richard-Cao** [comment]
@yuanyan

**Comment by rayliao** [comment]
>  Unknown option: base.stage
