### ISSUE TITLE
npm run demo 无法成功

### ISSUE THREAD

**Issue by mzkmzk** [taobaofed/react-web#76]
404-K:react-web maizhikun$ npm run demo

> react-web@0.2.4 demo /Users/maizhikun/Open_Source/react-web
> node local-cli/cli.js bundle webpack.config.js

/Users/maizhikun/Open_Source/react-web/node_modules/haste-resolver/lib/index.js:29
    preferNativePlatform: preferNativePlatform, preferNativePlatform: preferNa
                                                ^^^^^^^^^^^^^^^^^^^^
SyntaxError: Duplicate data property in object literal not allowed in strict mode
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/maizhikun/Open_Source/react-web/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/maizhikun/Open_Source/react-web/node_modules/haste-resolver/index.js:16:18)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/maizhikun/Open_Source/react-web/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "demo"
npm ERR! node v0.12.7
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! react-web@0.2.4 demo: `node local-cli/cli.js bundle webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-web@0.2.4 demo script 'node local-cli/cli.js bundle webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node local-cli/cli.js bundle webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/maizhikun/Open_Source/react-web/npm-debug.log

**Comment by SidFeng** [comment]
update your node

**Comment by mzkmzk** [comment]
1. `sudo npm install -g n`
2.  `sudo n stable`

更新node就可以了,THANKS

之前node是`v0.12.7`,更新了之后`v5.8.0`
